version: '3.1'

services:
  authservice:
    container_name: 'Ragequit.Auth'
    image: ragequit/auth
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '8232:8080'
    restart: always
    depends_on:
      - 'mariadb'
    networks:
      - intern
  mariadb:
    container_name: 'Ragequit.MariaDB'
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '<secure password>'
      MYSQL_DATABASE: 'ragequit_authservice'
      MYSQL_USER: 'authservice'
      MYSQL_PASSWORD: '<secure password>'
    volumes:
      - ~/mysql:/var/lib/mysql
    networks:
      - intern

networks:
  intern:
    driver: bridge
