version: '3.1'

services:
  authservice:
    container_name: 'Ragequit.Auth'
    image: ragequit/auth
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '8232:8080'
    restart: always
    depends_on:
      - 'mariadb'
    networks:
      - intern
    environment:
      PORT: '8080' # if you want to change the app port, you need to adjust the port in app.ts and in this file @line 11;
      DBUSER: 'authservice'
      DBPASS: 'SuperSecurePassword420'
      DBHOST: 'mariadb'
      DBPORT: '3306'
      DBRETRIES: '10'
      DBNAME: 'ragequit_authservice'
      NODE_MODE: 'development'
      JWT_SECRET: '<super secret>'
  mariadb:
    container_name: 'Ragequit.MariaDB'
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'SuperSecurePassword69'
      MYSQL_DATABASE: 'ragequit_authservice'
      MYSQL_USER: 'authservice'
      MYSQL_PASSWORD: 'SuperSecurePassword420'
    #volumes: # uncomment if you want a persistent storage.
    #  - ./mysql:/var/lib/mysql
    networks:
      - intern

networks:
  intern:
    driver: bridge
