version: "3.1"

services:
    authservice:
        container_name: "Ragequit.Auth"
        image: ragequit/auth
        build:
            dockerfile: Dockerfile
        ports:
            - "8232:8080"
        restart: always
        networks:
            - intern
    mongo:
        networks:
            - intern
        container_name: "MongoDB"
        image: mongo
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: mxu3gVuWU4UkPn
    mongo-express:
        networks:
            - intern
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: mxu3gVuWU4UkPn
networks:
    intern:
        driver: bridge

